### ISSUE TITLE
Linux install documentation

### ISSUE THREAD

**Issue by dedepene** [progre/nrf#7]
Hi, I'm having an issue with nrf under ubuntu 16.04. I downloaded the zip file, extracted and ran the nrf executable only to get the following error: "error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory"

Could you please provide some installation instructions for linux? Thanks!!!

**Comment by progre** [comment]
very sorry. linux version isn't confirmed operation. please try resolve yourself.

**Comment by dedepene** [comment]
OK, I think I got it running on Ubuntu now. What's the configuration URL though?

**Comment by progre** [comment]
Sorry, I don't  know the meaning of your question.
If you can't run nrf on Win or Mac, and you ask for a problem in linux only, i don't have an answer.
Travis build is success, so it is you will be able to build nrf your self.

**Comment by progre** [comment]
I will consider removing linux from the next build.
